### ISSUE TITLE
Moose collision/movement functionality needed

### ISSUE THREAD

**Issue by paulgatto** [sherpa-code/java2560game#3]
Requires #4 

Moose must travel from the left side of the screen to the right when spawned

Collision logic will be checked every tick while a moose exists.

The calculation will entail:
xPosMooseCollisionPoint = (xPos of the center of the moose sprite)+(spriteWidth/2)
If xPosMooseCollisionPoint >= car's hit point, game over

**Comment by sherpa-code** [comment]
movement needs to be resolved

**Comment by paulgatto** [comment]
moose still breaks as of #13, only when it hits the car. seems to stop the whole game loop

**Comment by paulgatto** [comment]
fixed as of #14
